#:schema https://raw.githubusercontent.com/mintyfrankie/brilliant-CV/main/metadata.toml.schema.json

# Set the output language
# INFO: value must matches folder suffix; i.e "zh" -> "./modules_zh"
language = "en"

[layout]
# Optional values: skyblue, red, nephritis, concrete, darknight
# You can also use a custom color by hex code i.e. "#1E90FF"
awesome_color = "skyblue"

# Skips are for controlling the spacing between sections and entries
before_section_skip = "1pt"
before_entry_skip = "1pt"
before_entry_description_skip = "1pt"

[layout.fonts]
regular_fonts = ["Source Sans 3"]
header_font = "Roboto"

[layout.header]
# Optional values: left, center, right
header_align = "left"

# Decide if you want to display profile photo or not
display_profile_photo = true

[layout.entry]
# Decide if you want to put your company in bold or your position in bold
display_entry_society_first = true

# Decide if you want to display organisation logo or not
display_logo = true

[inject]
# Decide if you want to inject AI prompt or not
inject_ai_prompt = true

# Decide if you want to inject keywords or not
inject_keywords = true
injected_keywords_list = [
    "Data Analyst",
    "C",
    "Python",
    "SQL",
    "C++",
    "Java",
    "AI",
    "Artifical Intelligence",
    "ML",
    "Machine Learning",
]

[personal]
first_name = "Eduard Antonovic"
last_name = "Occhipinti"

# The order of this section will affect how the entries are displayed
# The custom value is for any additional information you want to add, name it as custom-1, custom-2, etc.
[personal.info]
github = "eduardz1"
phone = "+39 340 8294310"
email = "occhipinti.eduard@icloud.com"
linkedin = "eduard-occhipinti-69b8b892"
orcid = "0009-0008-4050-2298"

# add a new section if you want to include the language of your choice
# i.e. [[lang.ru]]
# each section must contains the following fields
[lang.en]
header_quote = "Double degree Computer Engineering student looking for an internship in the AI&ML field"
cv_footer = "Curriculum vitae"
letter_footer = "Cover letter"
